---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: all
  require_chef_for_busser: false
  sudo_command: sudo -E -H
  additional_copy_path: tasks
  ansible_verbose: true
  ansible_verbosity: 3

transport:
  name: ssh
  max_ssh_sessions: 2

platforms:
  - name: bento/centos-7.3
  - name: bento/centos-6.9
  - name: box-cutter/fedora25
  - name: box-cutter/fedora24
  - name: box-cutter/ubuntu1404
  - name: box-cutter/ubuntu1604
  - name: box-cutter/ubuntu1610
  - name: ubuntu/zesty64
  - name: bento/debian-8.7
    provisioner:
      require_pip: true
      ansible_version: '2.3.0.0'
  - name: bento/debian-7.11
    provisioner:
      require_pip: true
      ansible_version: '2.3.0.0'
  - name: bento/opensuse-leap-42.2
    provisioner:
      python_sles_repo: http://download.opensuse.org/repositories/devel:/languages:/python/openSUSE_Leap_42.2/devel:languages:python.repo
      ansible_sles_repo: http://download.opensuse.org/repositories/systemsmanagement/openSUSE_Leap_42.2/systemsmanagement.repo
#  - name: Mitsutoshi-NAKANO/tumbleweed-ja
  - name: opensuse/openSUSE-Tumbleweed-x86_64
    provisioner:
      python_sles_repo: http://download.opensuse.org/repositories/devel:/languages:/python/openSUSE_Tumbleweed/devel:languages:python.repo
      ansible_sles_repo: http://download.opensuse.org/repositories/systemsmanagement/openSUSE_Tumbleweed/systemsmanagement.repo
  - name: maier/alpine-3.5-x86_64
    driver:
      vm_hostname: false
      cache_directory: false
#      synced_folders:
#        - [ "shared-folder", "/vagrant", "disabled: true"]
  - name: ogarcia/archlinux-x64
    driver:
      synced_folders:
        - [ "shared-folder", "/vagrant" ]
    provisioner:
      require_ansible_omnibus: true
      ansible_omnibus_url: file:///vagrant/ansible_install_arch.sh
      ansible_extra_flags: -e 'ansible_python_interpreter="/usr/bin/env python2"'
  - name: symbols/gentoo-minimal 
    driver:
      synced_folders:
        - [ "shared-folder", "/vagrant" ]
    provisioner:
      require_ansible_omnibus: true
      ansible_omnibus_url: file:///vagrant/ansible_install_gentoo-symbols.sh
      custom_pre_install_command: sudo /usr/bin/eselect python set python2.7
#  - name: cmiles/gentoo-amd64-minimal
#    driver:
#      customize:
#        memory: 8192
#        cpus: 4
#      provision: true
#      synced_folders:
#        - [ "shared-folder", "/vagrant", "group: 'users', type: :rsync" ]
#      cache_directory: false
#      vagrantfiles:
#        - Vagrantfile-GentooPreFlight.rb
#    provisioner:
#      require_ansible_omnibus: true
#      ansible_omnibus_url: file:///vagrant/ansible_install_gentoo.sh
  - name: kaorimatz/freebsd-11.0-amd64
    driver:
      synced_folders:
        - [ "shared-folder", "/vagrant", "type: :rsync"]
    provisioner:
      require_ansible_omnibus: true
      ansible_omnibus_url: file:///vagrant/ansible_install_freebsd.sh
      ansible_extra_flags: -e 'ansible_python_interpreter="/usr/bin/env python2.7"'
  - name: kaorimatz/freebsd-10.3-amd64
    driver:
      synced_folders:
        - [ "shared-folder", "/vagrant", "type: :rsync"]
    provisioner:
      require_ansible_omnibus: true
      ansible_omnibus_url: file:///vagrant/ansible_install_freebsd.sh
      ansible_extra_flags: -e 'ansible_python_interpreter="/usr/bin/env python2.7"'
  - name: kaorimatz/openbsd-6.0-amd64
    driver:
      synced_folders:
        - [ "shared-folder", "/vagrant", "type: :rsync"]
    provisioner:
      require_ansible_omnibus: true
      ansible_omnibus_url: file:///vagrant/ansible_install_openbsd.sh
      ansible_extra_flags: -e 'ansible_python_interpreter="/usr/bin/env python2.7"'
  - name: kaorimatz/openbsd-5.9-amd64
    driver:
      synced_folders:
        - [ "shared-folder", "/vagrant", "type: :rsync"]
    provisioner:
      require_ansible_omnibus: true
      ansible_omnibus_url: file:///vagrant/ansible_install_openbsd.sh
      ansible_extra_flags: -e 'ansible_python_interpreter="/usr/bin/env python2.7"'
  - name: Kralian/NetBSD_7.0_amd64
    driver:
      synced_folders:
        - [ "shared-folder", "/vagrant", "group: 'users', type: :rsync" ]
    provisioner:
      require_ansible_omnibus: true
      ansible_omnibus_url: file:///vagrant/ansible_install_netbsd.sh
      ansible_extra_flags: -e 'ansible_python_interpreter="/usr/pkg/bin/python2.7"'
      custom_pre_install_command: sudo ln -s /usr/pkg/bin/curl /usr/bin/curl
      sudo_command: /usr/pkg/bin/sudo
  - name: Kralian/netbsd_6.1.5_amd64
    driver:
      synced_folders:
        - [ "shared-folder", "/vagrant", "group: 'users', type: :rsync" ]
      ssh:
        shell: "/bin/sh"
    provisioner:
      require_ansible_omnibus: true
      ansible_omnibus_url: file:///vagrant/ansible_install_netbsd.sh
      ansible_extra_flags: -e 'ansible_python_interpreter="/usr/pkg/bin/python2.7"'
      custom_pre_install_command: sudo ln -s /usr/pkg/bin/python2.7 /usr/bin/python
      sudo_command: /usr/pkg/bin/sudo
  - name: b00ga/dragonfly46-hammer
    driver:
      vm_hostname: false
      cache_directory: false
      synced_folders:
        - [ "shared-folder", "/home/vagrant/vbox-shared", "type: :rsync"]
    provisioner:
      require_ansible_omnibus: true
      ansible_omnibus_url: file:///home/vagrant/vbox-shared/ansible_install_freebsd.sh
      ansible_extra_flags: -e 'ansible_python_interpreter="/usr/bin/env python2.7"'
  - name: hisa_x/oi-hipster-2016.10
    driver:
      vm_hostname: false
    provisioner:
      custom_pre_install_command: sudo -- curl -s -O https://pkgsrc.joyent.com/packages/SmartOS/bootstrap/bootstrap-2017Q1-x86_64.tar.gz  && sudo -- gtar -zxpf bootstrap-2017Q1-x86_64.tar.gz -C / && sudo -- /opt/local/bin/pkgin -y update && sudo -- /opt/local/bin/pkgin -y install ansible && sudo -- ln -s /opt/local/bin/ansible /usr/bin/ansible && sudo -- ln -s /opt/local/bin/ansible-playbook /usr/bin/ansible-playbook
  - name: kaorimatz/omnios-r151018
    driver:
      synced_folders:
        - [ "shared-folder", "/vagrant", "type: :rsync"]
    provisioner:
      require_ansible_omnibus: true
      ansible_omnibus_url: file:///vagrant/ansible_install_omnios.sh

suites:
  - name: default

verifier:
  ruby_bindir: /usr/local/ruby/kitchen/bin
  name: shell
  remote_exec: true
  command: ansible -c local -m setup localhost
