---
- name: Check if root CA certs are already installed
  find:
    paths: "/etc/openssl/certs"
    file_type: file
    recurse: no
    patterns: "*.pem"
  register: certsdir

- name: Install root CA certificates
  command: /usr/pkg/sbin/mozilla-rootcerts install
  when: certsdir.matched|int == 0
