---
# Git requires perl be updated to the latest
- name: Update all packages to latest
  pkgin:
    full_upgrade: yes

# Git can't download https urls without root ca store
- name: Install root certs package
  pkgin:
    name: "mozilla-rootcerts"
    state: present
- name: Install root CA certificates
  command: /usr/pkg/sbin/mozilla-rootcerts install

